name: dropai-starter
recipe: drupal10
config:
  webroot: web
  php: "8.3"
  conf:
    php: php.ini
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://dropai-starter.lndo.site"
  python:
    service: python
  pip:
    service: python
  flask:
    service: python
    description: Start the Python Flask app for local Python access in Drupal
    cmd: "python web/modules/contrib/dropai/modules/dropai_python/python/app.py"
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: >-
      rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2
      php-fpm
    user: root
  mongosh:
    service: vectordb
  atlas:
    service: vectordb
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
    build_as_root:
      - apt-get update -y
      - yes '' | pecl install mongodb
      - docker-php-ext-enable mongodb
    run_as_root:
      - echo "extension=mongodb.so" >> $PHP_INI_DIR/php.ini-production
  python:
    type: python:3.9
    build:
      - 'pip install -r web/modules/contrib/dropai/modules/dropai_python/python/requirements.txt'
    build_as_root:
      - apt-get update
      - apt-get install -y libgl1-mesa-glx libreoffice
    scanner:
      okCodes:
        - 502
  vectordb:
    type: lando
    api: 3
    meUser: root
    services:
      user: root
      image: mongodb/mongodb-atlas-local:latest
      command: 'entrypoint.sh start_atlas'
      entrypoint: [ "entrypoint.sh" ]
      privileged: true
      environment:
        LANDO_WEBROOT_USER: root
        LANDO_WEBROOT_GROUP: root
        LANDO_DROP_USER: root
        LANDO_NEEDS_EXEC: 'DOEEET'
        LOCALDEV_PASSWORD: psswd
      ports:
        - 27017:27017
      volumes:
        - data:/data/db
        - ./entrypoint.sh:/entrypoint.sh
    healthcheck: false
    build_as_root:
      - yum install -y mongodb-mongosh
      - yum install -y mongodb-atlas
    run:
      - atlas deployments setup dropai --bindIpAll --username root --password $LOCALDEV_PASSWORD --type local --port 27017 --force
      - mongosh --eval "use documents"
proxy:
  python:
    - python.lndo.site:5001
